import './FilterSearch.scss';

function FilterSearch() {
    return (
        <div className="wrapFilterSearch">
            <div className="d-flex">
                <select id="sapxep">
                    <option value="volvo">Sắp xếp</option>
                    <option value="volvo">Mới nhất</option>
                    <option value="saab">Mới cập nhật</option>
                    <option value="opel">Tiêu đề phim</option>
                </select>
                <select id="quocgia">
                    <option value="">Quốc gia</option>
                    <option value="phim-kr"> Phim (KR) </option>
                    <option value="phim-pl"> Phim (PL) </option>
                    <option value="phim-a-rap"> Phim Ả Rập </option>
                    <option value="phim-an-do"> Phim Ấn Độ </option>
                    <option value="phim-anh"> Phim Anh </option>
                    <option value="phim-ao"> Phim Áo </option>
                    <option value="phim-argentina"> Phim Argentina </option>
                    <option value="phim-au-my"> Phim Âu Mỹ </option>
                    <option value="phim-ba-lan"> Phim Ba Lan </option>
                    <option value="phim-belarus"> Phim Belarus </option>
                    <option value="phim-bi"> Phim Bỉ </option>
                    <option value="phim-bo-dao-nha"> Phim Bồ Đào Nha </option>
                    <option value="phim-brazil"> Phim Brazil </option>
                    <option value="phim-canada"> Phim Canada </option>
                    <option value="phim-chau-a"> Phim Châu Á </option>
                    <option value="phim-chau-au"> Phim Châu Âu </option>
                    <option value="phim-chau-phi"> Phim Châu Phi </option>
                    <option value="phim-chile"> Phim Chile </option>
                    <option value="phim-colombia"> Phim Colombia </option>
                    <option value="phim-dai-loan"> Phim Đài Loan </option>
                    <option value="phim-dan-mach"> Phim Đan Mạch </option>
                    <option value="phim-duc"> Phim Đức </option>
                    <option value="phim-ha-lan"> Phim Hà Lan </option>
                    <option value="phim-han-quoc"> Phim Hàn Quốc </option>
                    <option value="phim-hoa-ky"> Phim Hoa Kỳ </option>
                    <option value="phim-hong-kong"> Phim Hồng Kông </option>
                    <option value="phim-hungary"> Phim Hungary </option>
                    <option value="phim-hy-lap"> Phim Hy Lạp </option>
                    <option value="phim-iceland"> Phim Iceland </option>
                    <option value="phim-indonesia"> Phim Indonesia </option>
                    <option value="phim-iran"> Phim Iran </option>
                    <option value="phim-ireland"> Phim Ireland </option>
                    <option value="phim-israel"> Phim Israel </option> <option value="phim-khac"> Phim Khác </option>
                    <option value="phim-malaysia"> Phim Malaysia </option>
                    <option value="phim-mexico"> Phim Mexico </option>
                    <option value="phim-my"> Phim Mỹ </option>
                    <option value="phim-na-uy"> Phim Na Uy </option>
                    <option value="phim-nam-phi"> Phim Nam Phi </option>
                    <option value="phim-nam-trieu-tien"> Phim Nam Triều Tiên </option>
                    <option value="phim-nga"> Phim Nga </option>
                    <option value="phim-nhat-ban"> Phim Nhật Bản </option>
                    <option value="phim-nhat-ban-ban"> Phim Nhật Bản Bản </option>
                    <option value="phim-nigeria"> Phim Nigeria </option>
                    <option value="phim-pa-lan"> Phim Pa Lan </option>
                    <option value="phim-phan-lan"> Phim Phần Lan </option>
                    <option value="phim-phap"> Phim Pháp </option>
                    <option value="phim-philippines"> Phim Philippines </option>
                    <option value="phim-philippineses"> Phim Philippineses </option>
                    <option value="phim-quoc-gia-khac"> Phim Quốc gia khác </option>
                    <option value="phim-romania"> Phim Romania </option>
                    <option value="phim-sec"> Phim Séc </option>
                    <option value="phim-senegal"> Phim Senegal </option>
                    <option value="phim-singapore"> Phim Singapore </option>
                    <option value="phim-tay-ban-nha"> Phim Tây Ban Nha </option>
                    <option value="phim-thai-lan"> Phim Thái Lan </option>
                    <option value="phim-tho-nhi-ky"> Phim Thổ Nhĩ Kỳ </option>
                    <option value="phim-thuy-dien"> Phim Thụy Điển </option>
                    <option value="phim-thuy-si"> Phim Thụy Sĩ </option>
                    <option value="phim-trung-quoc"> Phim Trung Quốc </option>
                    <option value="phim-uae"> Phim UAE </option>
                    <option value="phim-uc"> Phim Úc </option>
                    <option value="phim-ukraina"> Phim Ukraina </option>
                    <option value="phim-viet-nam"> Phim Việt Nam </option>
                    <option value="phim-y"> Phim Ý </option>
                    <option value="quoc-gia-khac"> Quốc gia khác </option>
                    <option value="south-africa"> South Africa </option>
                    <option value="uk"> UK </option>
                    <option value="ukraine"> Ukraine </option>
                </select>
                <select id="theloai">
                    <option value="">Thể loại</option>
                    <option value="lgbtq"> Lgbtq+ </option>
                    <option value="phim-abenteuer"> Phim Abenteuer </option>
                    <option value="phim-action-adventure"> Phim Action &amp; Adventure </option>
                    <option value="phim-am-nhac"> Phim Âm Nhạc </option>
                    <option value="phim-animation"> Phim Animation </option>
                    <option value="phim-bi-an"> Phim Bí Ẩn </option>
                    <option value="phim-chien-tranh"> Phim Chiến Tranh </option>
                    <option value="phim-chieu-rap"> Phim Chiếu Rạp </option>
                    <option value="phim-chinh-kich"> Phim Chính Kịch </option>
                    <option value="phim-co-trang"> Phim Cổ Trang </option>
                    <option value="phim-familie"> Phim Familie </option>
                    <option value="phim-family"> Phim Family </option>
                    <option value="phim-gay-can"> Phim Gây Cấn </option>
                    <option value="phim-gia-dinh"> Phim Gia Đình </option>
                    <option value="phim-gia-tuong"> Phim Giả Tượng </option>
                    <option value="phim-giat-gan"> Phim Giật Gân </option>
                    <option value="phim-hai"> Phim Hài </option>
                    <option value="phim-hai-huoc"> Phim Hài Hước </option>
                    <option value="phim-hanh-dong"> Phim Hành Động </option>
                    <option value="phim-hinh-su"> Phim Hình Sự </option>
                    <option value="phim-historie"> Phim Historie </option>
                    <option value="phim-history"> Phim History </option>
                    <option value="phim-hoat-hinh"> Phim Hoạt Hình </option>
                    <option value="phim-hoc-duong"> Phim Học Đường </option>
                    <option value="phim-khoa-hoc"> Phim Khoa Học </option>
                    <option value="phim-khoa-hoc-vien-tuong"> Phim Khoa Học Viễn Tưởng </option>
                    <option value="phim-kich-tinh"> Phim Kịch Tính </option>
                    <option value="phim-kiem-hiep"> Phim Kiếm Hiệp </option>
                    <option value="phim-kinh-di"> Phim Kinh Dị </option>
                    <option value="phim-kinh-dien"> Phim Kinh Điển </option>
                    <option value="phim-komodie"> Phim Komödie </option>
                    <option value="phim-kriegsfilm"> Phim Kriegsfilm </option>
                    <option value="phim-krimi"> Phim Krimi </option>
                    <option value="phim-lang-man"> Phim Lãng mạn </option>
                    <option value="phim-lich-su"> Phim Lịch sử </option>
                    <option value="phim-liebesfilm"> Phim Liebesfilm </option>
                    <option value="phim-mien-tay"> Phim Miền Tây </option>
                    <option value="phim-music"> Phim Music </option>
                    <option value="phim-netflix"> Phim Netflix </option>
                    <option value="phim-phieu-luu"> Phim Phiêu Lưu </option>
                    <option value="phim-phim-gia-dinh"> Phim Phim Gia Đình </option>
                    <option value="phim-phim-hai"> Phim Phim Hài </option>
                    <option value="phim-phim-nhac"> Phim Phim Nhạc </option>
                    <option value="phim-romance"> Phim Romance </option>
                    <option value="phim-tai-lieu"> Phim Tài Liệu </option>
                    <option value="phim-tam-ly"> Phim Tâm Lý </option>
                    <option value="phim-than-thoai"> Phim Thần Thoại </option>
                    <option value="phim-the-loai-khac"> Phim Thể Loại Khác </option>
                    <option value="phim-the-thao"> Phim Thể Thao </option>
                    <option value="phim-tinh-cam"> Phim Tình Cảm </option>
                    <option value="phim-toi-pham"> Phim Tội Phạm </option>
                    <option value="phim-tu-lieu"> Phim Tư Liệu </option>
                    <option value="phim-tv-shows"> Phim Tv Shows </option>
                    <option value="phim-tv-film"> Phim TV-Film </option>
                    <option value="phim-tvb"> Phim Tvb </option>
                    <option value="phim-vien-tuong"> Phim Viển Tưởng </option>
                    <option value="phim-vo-thuat"> Phim Võ Thuật </option>
                    <option value="phim-war"> Phim War </option>
                    <option value="tam-lytinh-cam"> Tâm Lý,Tình Cảm </option>
                    <option value="the-loai-khac"> Thể Loại Khác </option>
                </select>
                <select id="nam">
                    <option value="2000">Năm</option>
                    <option value="2000">2000</option>
                    <option value="2001">2001</option>
                    <option value="2002">2002</option>
                    <option value="2003">2003</option>
                    <option value="2004">2004</option>
                    <option value="2005">2005</option>
                    <option value="2006">2006</option>
                    <option value="2007">2007</option>
                    <option value="2008">2008</option>
                    <option value="2009">2009</option>
                    <option value="2010">2010</option>
                    <option value="2011">2011</option>
                    <option value="2012">2012</option>
                    <option value="2013">2013</option>
                    <option value="2014">2014</option>
                    <option value="2015">2015</option>
                    <option value="2016">2016</option>
                    <option value="2017">2017</option>
                    <option value="2018">2018</option>
                    <option value="2019">2019</option>
                    <option value="2020">2020</option>
                    <option value="2021">2021</option>
                    <option value="2022">2022</option>
                    <option value="2023">2023</option>
                    <option value="2024">2024</option>
                    <option value="2025">2025</option>
                    <option value="2026">2026</option>
                </select>
                <div className="btnSearch">
                    <button type="submit">Lọc Phim</button>
                </div>
            </div>
        </div>
    );
}

export default FilterSearch;
